#use the official Nginx image as the base image
FROM nginx:latest
#Copy local nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf
# Expose ports.
EXPOSE 80
EXPOSE 8081
EXPOSE 7071
EXPOSE 9091
# Define default command.
CMD ["nginx", "-g", "daemon off;"]